apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: api
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: api
  source:
    repoURL: https://github.com/federicogmansilla/apps.git
    targetRevision: stage
    path: api
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: api
  syncPolicy:
    automated:
      selfHeal: true
