apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: statics
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/federicogmansilla/apps.git
    targetRevision: production
    path: statics
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: statics
  syncPolicy:
    automated:
      selfHeal: true
