apiVersion: v1
kind: Namespace
metadata:
  name: statics
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: statics
spec:
  selector:
    matchLabels:
      run: statics
  replicas: 1
  template:
    metadata:
      labels:
        run: statics
    spec:
      containers:
      - name: statics
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
          - name: static-html
            mountPath: /usr/share/nginx/html/statics
      volumes:
        - name: static-html
          configMap:
            name: static-html
---
apiVersion: v1
kind: Service
metadata:
  name: statics
  labels:
    run: statics
spec:
  ports:
  - port: 80
    protocol: TCP
  type: LoadBalancer
  selector:
    run: statics
